### ISSUE TITLE
Build Failed when adding new components 

### ISSUE THREAD

**Issue by MeteorCoder** [AppyBuilder/AppyBuilder-Source#28]
A few days ago I started to work with a new source of Appybuilder as I couldn't figure out where the issue was coming from. As of yesterday I've restarted again. What happens is when adding a Java file into my own folder or appinventors component folder, it doesn't seem to translate the blocks. So I have to add them to OdeMessages.java myself. When I do so I build and get the below error. If I try ant extensions it says when in the Dev server that form couldn't be found. I don't know what to do. Can anyone help?

[java] INFO: The current progress is 85%
     [java] com.android.sdklib.build.ApkCreationException: java.io.FileNotFoundException: C:\Users\meteo\AppData\Local\Temp\1556938158416_0.09805427963311308-0\youngandroidproject\..\build\tmp\classes.dex does not exist
     [java]     at com.android.sdklib.build.ApkBuilder.init(ApkBuilder.java:469)
     [java]     at com.android.sdklib.build.ApkBuilder.<init>(ApkBuilder.java:396)
     [java]     at com.android.sdklib.build.ApkBuilder.<init>(ApkBuilder.java:333)
     [java]     at com.google.appinventor.buildserver.Compiler.runApkBuilder(Compiler.java:1179)
     [java]     at com.google.appinventor.buildserver.Compiler.compile(Compiler.java:1063)
     [java]     at com.google.appinventor.buildserver.ProjectBuilder.build(ProjectBuilder.java:178)
     [java]     at com.google.appinventor.buildserver.Main.main(Main.java:85)
     [java] Caused by: java.io.FileNotFoundException: C:\Users\meteo\AppData\Local\Temp\1556938158416_0.09805427963311308-0\youngandroidproject\..\build\tmp\classes.dex does not exist
     [java]     at com.android.sdklib.build.ApkBuilder.checkInputFile(ApkBuilder.java:938)
     [java]     at com.android.sdklib.build.ApkBuilder.init(ApkBuilder.java:440)
     [java]     ... 6 more
     [java] May 03, 2019 11:08:38 PM com.google.appinventor.buildserver.Compiler runApkBuilder
     [java] WARNING: YAIL compiler - ApkBuilder failed.

BUILD FAILED
C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build.xml:21: The following error occurred while executing this line:
C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\buildserver\build.xml:261: Java returned: 1

Total time: 47 minutes 3 seconds

**Comment by Amerkashi** [comment]
You mentioned "My own folder". What do you mean by this? Also, check to see if you have other error messages.

**Comment by MeteorCoder** [comment]
There are no other messages. 

What I meant by my own folder was like `ml > meteorcoder > componentName.java`. An example would be `com > appybuilder > DateUtils > DateUtils.java`.

**Comment by MeteorCoder** [comment]
Solved!

Removed all components in `com > appybuilder` and it builds successfully. No error about `Form` not being there anymore.

**Comment by MeteorCoder** [comment]
Great!

It's back with 

```
[java] INFO: The current progress is 80%
     [java] May 04, 2019 8:11:23 PM com.google.appinventor.buildserver.Execution execute
     [java] INFO: ____Executing C:\Program Files\Java\jdk1.8.0_201\jre/bin/java -mx824M -jar C:\Users\meteo\AppData\Local\Temp\dx_423939066163896918.jar --dex --positions=lines --force-jumbo --output=C:\Users\meteo\AppData\Local\Temp\1557013924395_0.4376822238008917-0\youngandroidproject\..\build\tmp\classes3.dex C:\Users\meteo\AppData\Local\Temp\google-play-services995269688085331983.jar
     [java] Converting compiled files and external libraries into C:\Users\meteo\AppData\Local\Temp\1557013924395_0.4376822238008917-0\youngandroidproject\..\build\tmp\classes3.dex...
     [java] May 04, 2019 8:12:16 PM com.google.appinventor.buildserver.Compiler setProgress
     [java] INFO: The current progress is 82%
     [java] May 04, 2019 8:12:16 PM com.google.appinventor.buildserver.Compiler runDx
     [java] INFO: DX time: 1118.063 seconds
     [java] May 04, 2019 8:12:16 PM com.google.appinventor.buildserver.Compiler setProgress
     [java] INFO: The current progress is 85%
     [java] com.android.sdklib.build.ApkCreationException: java.io.FileNotFoundException: C:\Users\meteo\AppData\Local\Temp\1557013924395_0.4376822238008917-0\youngandroidproject\..\build\tmp\classes.dex does not exist
     [java]     at com.android.sdklib.build.ApkBuilder.init(ApkBuilder.java:469)
     [java]     at com.android.sdklib.build.ApkBuilder.<init>(ApkBuilder.java:396)
     [java]     at com.android.sdklib.build.ApkBuilder.<init>(ApkBuilder.java:333)
     [java]     at com.google.appinventor.buildserver.Compiler.runApkBuilder(Compiler.java:1179)
     [java]     at com.google.appinventor.buildserver.Compiler.compile(Compiler.java:1063)
     [java]     at com.google.appinventor.buildserver.ProjectBuilder.build(ProjectBuilder.java:178)
     [java]     at com.google.appinventor.buildserver.Main.main(Main.java:85)
     [java] Caused by: java.io.FileNotFoundException: C:\Users\meteo\AppData\Local\Temp\1557013924395_0.4376822238008917-0\youngandroidproject\..\build\tmp\classes.dex does not exist
     [java]     at com.android.sdklib.build.ApkBuilder.checkInputFile(ApkBuilder.java:938)
     [java]     at com.android.sdklib.build.ApkBuilder.init(ApkBuilder.java:440)
     [java]     ... 6 more
     [java] May 04, 2019 8:12:16 PM com.google.appinventor.buildserver.Compiler runApkBuilder
     [java] WARNING: YAIL compiler - ApkBuilder failed.
```

HOWEVER A PREVIOUS ERROR SHOWS:
```
     [java] INFO: ____Executing C:\Program Files\Java\jdk1.8.0_201\jre/bin/java -mx824M -jar C:\Users\meteo\AppData\Local\Temp\dx_423939066163896918.jar --dex --positions=lines --force-jumbo --output=C:\Users\meteo\AppData\Local\Temp\1557013924395_0.4376822238008917-0\youngandroidproject\..\build\tmp\classes.dex C:\Users\meteo\AppData\Local\Temp\1557013924395_0.4376822238008917-0\youngandroidproject\..\build\classes C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-b3fb61d5634954dd567170a7d225311a.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-4afd1465d334dee94ac700edb0374a45.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-5afa64929f2a5ae21b3f4e662c5134b9.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-78d6843076226f017df3cba74f5536d4.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-9e6926c20fded33b9d666f9ceb5fda47.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-a6624c325dd150cdd39dd94d5877723f.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-deb65eafbb152f9e48d8d71bb987610b.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-d7824d6abd76553e459bdb67e5d655cf.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-99772b87696f7d55cfd38944ea69fbc0.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-bdc880853f2b3cc524bfb71a398684a8.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-d6dade351539cb73bc23c3b21f17a2f6.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-72585696ee55368ffe3c42043b74a7bc.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-4a0e85a8dc1a65c8307f3894186ac52e.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-c282190f341f66bb71bbbbef1d756145.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-9fdd621a8be2ade6dae94a82e5656dbb.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-edb9481c6eee07f4feaa61502af855da.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-3648c2fb06d9e76cefd3f3278962f3d6.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-b0ad2fc8d30a8280dd8d2553e203079d.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-b03e09cae196efc1b0c0b3794f51c326.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-c4ad73278bbd35326c3cc0f7c0aa378a.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-0063e1e73317010f6523a61c6aec0a1a.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-ac4cf27497116ecf2b530b9d7975ec0b.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-6a94bf1e6d25352591a8f118c9df00f9.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-50376604002609b65556571e82e56cbc.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-9161ee85b347afd51b880dcb15ce045c.jar C:\Users\meteo\Desktop\Appybuilder\AppyBuilder-Source\appinventor\build\buildserver\dexCache\dex-cached-74cb89170043cab684894fcc9aeaec98.jar
     [java] Converting compiled files and external libraries into C:\Users\meteo\AppData\Local\Temp\1557013924395_0.4376822238008917-0\youngandroidproject\..\build\tmp\classes.dex...
     [java]
     [java] UNEXPECTED TOP-LEVEL EXCEPTION:
     [java] com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
     [java]     at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:484)
     [java]     at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:261)
     [java]     at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:473)
     [java]     at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:161)
     [java]     at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
     [java]     at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
     [java]     at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
     [java]     at com.android.dx.command.dexer.Main.run(Main.java:277)
     [java]     at com.android.dx.command.dexer.Main.main(Main.java:245)
     [java]     at com.android.dx.command.Main.main(Main.java:106)
     [java]
     [java] Converting compiled files and external libraries into C:\Users\meteo\AppData\Local\Temp\1557013924395_0.4376822238008917-0\youngandroidproject\..\build\tmp\classes3.dex...
```

**Comment by MeteorCoder** [comment]
I changed the descriptions of some components which didn't math `OdeMessages.java` and I'm too lazy to change them now so I changed them back to `xxxxxx Update OdeMessages` and it works.
